title = "Red Hat | Public Sector"
baseURL = "http://redhatgov.io/"
theme = "redhatgov"
languageCode = "en-us"
metaDataFormat = "yaml"

[params]
    description = "Tried. Tested. Trusted."

[taxonomies]
    workshop = "workshops"

[blackfriday]
    smartypants = false

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Workshops"
    identifier = "workshops"
    weight = 100

[[menu.main]]
    name = "Junior SA Program"
    identifier = "jr-sa"
    url = "https://events.redhat.com/profile/form/index.cfm?PKformID=0x110847abcd"
    weight = 90
